name: Build iOS (unsigned .ipa)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios-unsigned:
    runs-on: macos-latest
    env:
      # Only set the channel; DO NOT set FLUTTER_VERSION (remove any FLUTTER_VERSION="latest")
      FLUTTER_CHANNEL: "stable"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (stable channel)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Verify flutter
        run: |
          flutter --version
          flutter doctor -v

      - name: Install Ruby gems (CocoaPods)
        run: |
          # Install CocoaPods (version selection optional)
          sudo gem install cocoapods || true
          pod --version

      - name: flutter pub get
        run: flutter pub get

      - name: Prepare iOS pods
        working-directory: ios
        run: |
          pod repo update --silent || true
          pod install --silent

      - name: Build iOS (no codesign)
        run: |
          # Build iOS without code signing
          flutter build ios --release --no-codesign

      - name: Locate built .app
        run: |
          set -eux
          APP_PATH="build/ios/iphoneos/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found at $APP_PATH. Listing build/ios:"
            ls -la build/ios || true
            exit 1
          fi
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV

      - name: Package unsigned .ipa
        run: |
          set -eux
          rm -rf Payload unsigned.ipa
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          # Create unsigned IPA by zipping the Payload folder
          zip -r unsigned.ipa Payload
          ls -lh unsigned.ipa

      - name: Upload unsigned .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ios-ipa
          path: unsigned.ipa
